ausocean/cloud

- cmd/datablue/handlers.go
- cmd/datablue/main.go
This is more code copied from VidGrind.
A few of the errors have been wrapped, but otherwise it is unchanged.
> Added apiHandler

- cmd/oceanbench/main.go
- cmd/oceanbench/s/footer.html
- cmd/oceanbench/t/footer.html
The footer is now a template (fragment), not a static file. This implements Issue #23.
> Move footer

- model/actuator.go
- model/binary.go
- model/credential.go
- model/cron.go
- model/cron_test.go
- model/device.go
- model/entities.go
- model/media.go
- model/model_test.go
- model/mtsmedia.go
- model/scalar.go
- model/sensor.go
- model/sensor_test.go
- model/site.go
- model/text.go
- model/user.go
- model/variable.go
Datastore models ported from https://bitbucket.org/ausocean/iotsvc/iotds.
Models now use https://github.com/ausocean/openfish/datastore directly and the shim has been removed.
> Initial revision

- cmd/datablue/handlers.go
This was done because it was rather hard to debug errors being returned to ESP clients without redeploying datablue in debug mode (undesirable).
> cmd/datablue/handlers.go: log device error responses regardless of debug

- cmd/oceantv/broadcast_states.go
Once we successfully create broadcast when we enter the vidforwardSecondaryStarting state, we will call Stream on the forwarding service so that the RTMP endpoints are updated (the implementation of Stream should provide the forwarding service with the create RTMP endpoints).
> Call fwd.Stream on vidfowardSecondaryStarting entry

- cmd/oceantv/broadcast_states.go
This step was inadvertently left out; the whole point of secondary broadcasts is that they stop.
> Stop secondary broadcasts when live state exited

- cmd/oceanbench/main.go
This is done to support running oceanbench locally using the datstore (not standalone).
> oceanbench/main.go: if environment is not appengine, use project level template path

- cmd/oceantv/broadcast.go
- cmd/oceantv/broadcast/youtube.go
- cmd/oceantv/broadcast_events.go
- cmd/oceantv/broadcast_events_test.go
- cmd/oceantv/broadcast_hardware_machine.go
- cmd/oceantv/broadcast_hardware_machine_test.go
- cmd/oceantv/broadcast_machine_test.go
- cmd/oceantv/broadcast_manager.go
- cmd/oceantv/broadcast_permanent.go
- cmd/oceantv/broadcast_service.go
- cmd/oceantv/broadcast_states.go
- cmd/oceantv/health.go
- cmd/oceantv/main.go
- cmd/oceantv/utils.go
Addresses issue #16 
There were a lot of calls to "log.Printf" of the form "Broadcast: %s, id: %s ....", so we're factoring this pattern out. We're doing this by requiring that most interfaces that the broadcast code uses take a "log" parameter of type func(string,...interface{}). This means that we can pass around a log function that wraps any messages provided with the broadcast name and id.
We're now also using this in areas where the broadcast name and id were not specified. This means that all logging related to a particular broadcast is labelled as such.
> Overhaul logging for broadcast code

- cmd/oceanbench/api.go
- cmd/oceanbench/main.go
- cmd/oceancron/cron.go
- cmd/oceancron/main.go
- cmd/oceantv/broadcast_states.go
- cmd/oceantv/health.go
- cmd/oceantv/main.go
- notify/notify.go
- notify/notify_test.go
- notify/options.go
- notify/timestore.go
This implements the Notify package support for Issue #77 .
Note that **SendOps** is now deprecated as the functionality can be readily achieved by initializing a **Notifier** with the _WithRecipient_ option set to the ops email address. The GetOpsEnvVars helper function has been added to make this a bit easier.
> Notifier options

- cmd/oceantv/broadcast.go
- cmd/oceantv/broadcast_manager.go
- cmd/oceantv/broadcast_test.go
- cmd/oceantv/health.go
We're essentially copying handleHealthWithCallback into the HandleHealth method of the OceanBroadcastManager and changing the interface to follow the callback pattern. Subsequently we're now using HandleHealth instead for the healthStatusCheckEvent handling.
We're also removing the old handleHealth function which is now dead code.
> Use callback health handling in broadcast manager

- cmd/oceantv/broadcast.go
- cmd/oceantv/broadcast_manager.go
- cmd/oceantv/broadcast_test.go
- cmd/oceantv/health.go
Depends on PR #92 
Resolve issue #78 
We used to email on any issue, even if it might have been just temporary. This is uneccessary and creates false concerns. So now we're only performing email notification on consecutive issues.
This has involved modifying how we check for issues i.e. we return the string of the issue rather than a bool. We also provide this to the badHealthCallback, where we can handle with health notification if we wish.
> Only email notify on consecutive bad health issues

- cmd/oceantv/broadcast.go
- cmd/oceantv/broadcast_manager.go
- cmd/oceantv/broadcast_test.go
Depends on PR #94 
Resolves issue #75
It turns out that we weren't getting any badHealthEvents published and subsequently never transitioning to the Unhealthy states because we weren't actually saving the changes to the issues tally to the datastore. This change fixes this.
It has required that we alter the interface of HandleHealth slightly to require a parameter of Store interface type.
> Save broadcast issues tally

- cmd/oceantv/broadcast_machine_test.go
- cmd/oceantv/broadcast_states.go
- cmd/oceantv/broadcast_states_test.go
Depends on PR #95 
The behaviour has been incorrect. To start, we should not stop the broadcast on exit of the directLive state. Maybe once upon a time this worked because there was no state other than idle that we'd exit to, but now we have a directLiveUnhealthy. So, we only try to stop the broadcast (if exists) on entry to directIdle.
Secondly, the directLiveUnhealthy similarly should not try to stop the broadcast on exit. It should also implement the fixable state so that it can try to fix the hardware in this state.
> Fix direct state behaviour

- cmd/oceantv/broadcast.go
- cmd/oceantv/broadcast_hardware_machine.go
Depends on PR #96 
Up until this point there has been no way to know if a start failure happened specifically because the hardware failed to start.
We're fixing this by having the hardwareStarting state implement the stateWithTimeout interface so that when it times out we can emit a hardwareStartFailureEvent and precisely indicate the cause of failure.
This has required that we now save hardware state data, so there's a new field of the config called HardwareStateData. It has required that we add JSON marshalling tags to the other states.
> Implement stateWithTimeout for hardwareStarting

- cmd/oceantv/broadcast_machine.go
- cmd/oceantv/broadcast_machine_test.go
- cmd/oceantv/broadcast_states.go
Depends on PR #97 
This should not happen under normal circumstances given that we now report start failure on both broadcast live transition issues and hardware camera startup failures, but it will cover us with any other unforseen conditions.
We're modifying the timeout to 10 minutes, which will give the hardware enough time to timeout (5 minutes).
> Report start failure on starting state timeout

- cmd/oceanbench/broadcast.go
- cmd/oceanbench/t/broadcast.html
- cmd/oceantv/broadcast.go
The broadcast config now contains the controller MAC allowing the state machine to make queries about the status of the controller.
This value is also read from the broadcast page.
> OceanTV: Add controller MAC to broadcast config

- cmd/oceantv/broadcast/auth.go
oauth2.NoContext is reported to be deprecated; context.Background() is suggested.
> Use background context for token exchange

- cmd/oceantv/broadcast.go
- cmd/oceantv/broadcast/auth.go
- cmd/oceantv/broadcast/youtube.go
- cmd/oceantv/broadcast_manager.go
- cmd/oceantv/broadcast_service.go
- cmd/oceantv/broadcast_test.go
- cmd/oceantv/health.go
- cmd/oceantv/main.go
- utils/utils.go
The bucket object containing the required auth tokens for YouTube Live API usage was hardcoded to that belonging to AusOcean's account, however, we now require the ability to change this depending on the YouTube account for which we want to broadcast to.
We're now storing the Account email in the broadcast config, and using this according to a schema for the object name, which a common function, TokenURIFromAccount enforces. We provide this to the YoutTubeBroadcast service which will use it to get the auth token where required.
These changes also affect health checking and chat message posting
so to make things better, we're incorporating this functionality
into the broadcast manager/broadcast services.
> Parameterise auth token URI for broadcast

- cmd/oceanbench/broadcast.go
- cmd/oceanbench/t/broadcast.html
- oceanbench.yaml
Depends on PR #134
Resolves issue #131 
To associate and authenticate a broadcast with a particular YouTube account, we need to generate a token for the account.
We're providing a button on the broadcast page that performs the generation and stores the account email in the broadcast config, which can be used to later retreive the token for refresh and/or use.
> Add token generation button to broadcast page

- cmd/oceanbench/broadcast.go
- cmd/oceanbench/t/broadcast.html
The channel field will show the current account associated with the broadcast config. This will show the current channel that the stream will be sent to. This also ensures that the current account stays associated with the broadcast rather than being overwritten by a null value.
Addresses (#147)
Requires (#148)
> Bench: Add channel field to broadcast UI (#147)

- cmd/oceanbench/broadcast.go
- cmd/oceanbench/t/broadcast.html
The broadcast UI now makes use of radio buttons for common settings with limited options (resolution and privacy). These settings can also be easily updated within broadcast.go by updating the request struct with new options.
> Bench: Broadcast UI radio buttons

- cmd/oceanbench/s/broadcast.js
- cmd/oceanbench/t/broadcast.html
This change hides advanced options on the broadcast page by default. These options can be shown by clicking the advanced options checkbox.
This code also adds a cookie for the advanced option checkbox so that the setting persists across reloads.
The settings that are shown by default:
> Bench/Broadcast: Hide advanced options (#151)

- cmd/oceanbench/s/main.css
- cmd/oceanbench/t/broadcast.html
- cmd/oceanbench/t/set/device.html
The broadcast page UI has been updated to be more logically ordered, and using bootstrap styling to match the site more seamlessly.
This is just a styling change. (I can separate the PR into commits if that is preferred, but they are all mostly pretty huge due to the indent changing of the formatter.)
> Bench/Broadcast: Update Broadcast UI

- cmd/datablue/handlers.go
- cmd/datablue/main.go
- The response code (rc) and client type (ct) are now included in config responses.
- Config requests now clear the device status only when an upgrade completes.
> Include response code in config request

- cmd/oceanbench/broadcast.go
- cmd/oceanbench/t/broadcast.html
- cmd/oceantv/broadcast.go
- cmd/oceantv/broadcast_events.go
- cmd/oceantv/broadcast_machine.go
- cmd/oceantv/broadcast_machine_test.go
- cmd/oceantv/broadcast_states.go
- cmd/oceantv/broadcast_states_test.go
- cmd/oceantv/utils.go
Resolves issue #157 
We're now allowing only limited health fixes when in the permanent live unhealthy state. Fixes include hardware reset and requesting the forwarding service for stream (in case problems are on this front).
In the case that we max out our fixes allowance, we transition to a new permanent failure state. In this state we request that the forwarder goes to slate mode. We've also introduced a state to the broadcast object "InFailure" which is true if the broadcast is in a failure state. This is accessible from the broadcast UI. We'll need to uncheck this once we've resolved any issues and would like to resume normal behaviour.
> Improve permanent live unhealthy state behaviour

- cmd/oceanbench/broadcast.go
- cmd/oceanbench/s/main.js
- cmd/oceanbench/t/broadcast.html
This was done because the javascript was being used that interpreted the UTC offset string as a decimal, which caused the time to be off by an 30 minutes. This change should fix that.
The site's timezone can be used to keep things consistent and avoid error from user input.
> bench: use site timezone for broadcast, don't expect offset decimal

- cmd/oceantv/broadcast_machine.go
- cmd/oceantv/broadcast_machine_test.go
Resolves #156
We're making the error handling behaviour a little smarter when it comes to error condition behaviour. For many of these cases, we were transitioning to the idle state, but this isn't great for a permanent broadcast.
Firstly, if we time out transitioning from live to slate, we're now notifying ops to check fordwarder software and staying in the live state.
Secondly, if we time out on permanent starting, we use the onFailure closure which gives us some more chances, but will notify and disable when a limit is reached.
Thirdly, if we time out transitioning from slate to live, we enter the permanent failure state which stays in slate mode and notifies ops that there may be a problem with the hardware.
> Improve permanent start/transition error behaviour

- cmd/oceanbench/broadcast.go
- cmd/oceantv/broadcast/youtube.go
Broadcast.go now calls AuthToken which first checks if a token for the given user already exists.
- If the token exists, the call returns
- If the token does not exist, the call generates a new token and saves it using GenerateToken.
This will prevent subsequent token generations of tokens which will not have refresh tokens (as only the first token will come with a refresh token).
> Bench: Check for existing token before generating new token (#158)

- notify/notify.go
- notify/notify_test.go
This is a simple change to improve typesafe usage of the `notify` package, which is backwards compatible with clients, providing the kind is supplied as literal.
I considered making `Kind` an interface (modeled on `Error`), but that would not be backwards compatible. Further, it is not clear that `Kind` needs to be more than a string.
> Added type Kind

- cmd/oceantv/broadcast_machine.go
- cmd/oceantv/broadcast_states.go
closes #54 
We're now handling hardware failure events when we're in the permanent live/live unhealthy and slate to live states. Under these circumstances, we should stay in slate. We can do this by entering the vidforwardPermanentInFailure state in which case we wait until admin has taken the broadcast out of this state i.e. maybe fixed the problem.
> Slate on hardware failure for permanent live states

- cmd/oceantv/broadcast.go
- cmd/oceantv/broadcast_hardware_machine.go
- cmd/oceantv/broadcast_hardware_machine_test.go
- cmd/oceantv/broadcast_machine.go
- cmd/oceantv/broadcast_machine_test.go
- cmd/oceantv/broadcast_manager.go
- cmd/oceantv/broadcast_states.go
- cmd/oceantv/broadcast_test.go
- cmd/oceantv/main.go
- cmd/oceantv/utils.go
closes #177 
We're having OceanBroadcastManager.Save wrap
updateConfigWithTransaction, which achieves several things.
Firstly, if everything uses OceanBroadcastManager.Save for updating broadcast config fields, then we'll have everything inherently synchronised propertly.
Secondly, this should greatly reduce boilerplate associated with using updateConfigWithTransaction for every modifification of the broadcast config.
> Merge broadcast man save and config update transaction

- cmd/oceantv/broadcast_events.go
- cmd/oceantv/broadcast_hardware_machine.go
- cmd/oceantv/broadcast_machine.go
- cmd/oceantv/broadcast_states.go
createBroadcastAndRequestHardware now makes a call to getDeviceStatus for the controller to ensure that the controller will even respond to hardware start events before trying to create a new broadcast. This will give a pretty good indicator that the controller is not powered, likely due to a low power event on the rig.
> OceanTV: Check status of controller before starting broadcast (#114)

- cmd/oceanbench/set.go
- model/device.go
Device type constants are now stored in model/device.go and exported.
> Model: Move device types to model

- cmd/oceanbench/admin.go
- cmd/oceanbench/main.go
- cmd/oceanbench/t/admin.html
- model/site.go
This adds `Description`, `OrgID`, `OpEmail` and `YouTubeEmail` to `Site` entity. 
Implements Issue #188.
> Support for Site V3

- cmd/oceantv/utils.go
The Save method in the OceanBroadcastManager now wraps the updateConfigWithTransaction function.  This means that it will also have to handle saving of an entirely new broadcast configuration.
We now use store.Create to create a broadcast variable if we get an ErrNoSuchEntity error on update, and then try the update again.
> Create broadcast variable if not exist on update

- cmd/oceanbench/broadcast.go
- cmd/oceanbench/main.go
This change uses the constant device types from model to ensure that the device type comparison is matching correctly.
> Bench: Use constants for device types on broadcast page.

- cmd/oceantv/main.go
- cmd/oceantv/utils.go
When saving a new broadcast, errors coming from cloudstore are now properly matched with the correct types from cloud.google.com/go/datastore.
This change also changes the updateConfig function since there will be no config to unmarshal
NOTE:
This is currently deployed to fix a P0 level bug
closes #213
> TV: Fix error matching for ErrNoSuchEntity

- cmd/oceancron/main.go
This was done so that we can quickly tell what version is running and revert to known working versions if needed.
> cron: add version and display on index page

- cmd/datablue/main.go
- cmd/oceanbench/main.go
- cmd/oceancenter/main.go
- cmd/oceancron/main.go
- cmd/oceantv/main.go
Also ensured that all of the default ports  in standalone mode are different:
- oceanbench 8080
- oceancron 8081
- oceantv 8082
- datablue 8083
- oceancenter 8084
Implements Issue #115
> Added --filestore command line flag to specify file store path

- cmd/datablue/handlers.go
- model/device.go
With this change, it is possible to programmatically set the device status by setting a variable called `status` to a value between 0 and 7 (as defined in `device.go`).
This will be most useful in conjunction with cron jobs. For example, to force a device to reboot, set the variable `<device.mac-address>.status` to the value `2`.
> Device status var

- cmd/oceanbench/broadcast.go
- cmd/oceantv/broadcast.go
- cmd/oceantv/broadcast_machine.go
- cmd/oceantv/broadcast_machine_test.go
- cmd/oceantv/broadcast_states.go
- cmd/oceantv/broadcast_states_test.go
- cmd/oceantv/main.go
This change performs some cleaning up of the BroadcastConfig struct. We remove some fields that are unused i.e. StartTime, EndTime, CamOn and CamOff, and also relocate LastStatusCheck, LastChatMsg and LastHealthCheck, given that these are state specific and can be part of the state data. Moving the lastBlah states was most easily done by embedding a couple of structs with common fields into states that require these, and have these implement an interface to allow access of these fields.
> Remove unused or inappropriate config fields

- cmd/oceanbench/broadcast.go
- cmd/oceanbench/main.go
- cmd/oceantv/broadcast.go
- cmd/oceantv/main.go
This was done because CreateBroadcast no longer uses the saveBroadcast function that checks the cron. But we still want the cron to be checked whena broadcast is created.
Addresses issue #232.
> tv: move auto add checkbroadcast cron to CreateBroadcast

- model/factories.go
This change adds factories to create the following variables (with passed values)
- AlarmNetwork
- AlarmPeriod
- AlarmRecoveryVoltage
- AlarmVoltage
- AutoRestart
- Power1
- Power2
- Power3
- Pulses
- PulseWidth
- PulseCycleVar
- PulseSuppress
It is up to the caller to define the value of the variable for most of these factories. I think this makes more sense, as the system layer will be making the decision about what the default values look like.
depends on #207
> Model: Add variable factories (#206)

- cmd/oceanbench/broadcast.go
A recent change meant that we were trying to return a value in a function where no value was expected. We are now calling reportError, then returning.
> Bench: Fix error handling in broadcast.go

- cmd/oceanbench/main.go
- cmd/oceanbench/ts/header-group.ts
This change moves the site menu to a new line in the header to prevent it from overlapping with the logout button on mobile.
> Bench: Fix Mobile UI

- cmd/oceantv/broadcast.go
- cmd/oceantv/broadcast_hardware_machine_test.go
- cmd/oceantv/broadcast_machine_test.go
- cmd/oceantv/broadcast_states.go
- cmd/oceantv/broadcast_states_test.go
- cmd/oceantv/broadcast_test.go
- cmd/oceantv/main.go
- cmd/oceantv/utils.go
Depends on PR #242 
This change aims to improve aspects of the broadcast testing facilities.
To start, we're adding logOutput and notifier fields to the broadcastContext. This will allow us to specify different log and notification implementations for the context. For example t.Log and a mock notifier implementation when testing.
We're also now providing some factories for common broadcast context arrangements.
We've added mock eventBus and notifier implementations, and a log output implementation, logRecorder, which will allow us to validate logging.
Some other smaller changes:
* unexporting the dummyManager
* modifying dummyManager.Save method to better reflect our real implementation.
* providing constructors for the dummyService and dummyStore implementations
> Improve testing facilities

- cmd/oceantv/broadcast_events.go
- cmd/oceantv/broadcast_hardware_machine.go
- cmd/oceantv/broadcast_machine.go
- cmd/oceantv/broadcast_machine_test.go
- cmd/oceantv/broadcast_manager.go
- cmd/oceantv/broadcast_states.go
- cmd/oceantv/broadcast_test.go
- cmd/oceantv/main.go
Depends on PR #244 
We're starting with checking the hardware is defined for a given broadcast, otherwise we disable. We're doing this with an invalidConfigurationEvent. This can be used for various configuration issues, and for convenience also impelements the error interface.
We're adding a basic test case that highlights the ease of integration type testing using the new broadcastSystem abstraction added in the prior change.
> Start adding configuration sanitisation

- .github/workflows/go.yml
This change adds testing to GitHub for all pull requests to the main branch. This should help to flag issues in PRs before they are merged to main.
NOTE: This is the default GitHub implementation with slight changes for our current go version.
> Actions: Add go testing

- cmd/oceanbench/main.go
- cmd/oceanbench/s/main.js
This was done because the time was losing 30 minutes due to a misinterpretation of the timezone.
Closes #261
> bench: ensure timezone is applied correctly when converting from timestamp to date

- cmd/oceanbench/broadcast.go
- cmd/oceanbench/main.go
This was done because it is hard to tell is an operation has been performed successfully.
Closes issue #253 
messages have also been added for slate upload and authentication of a new channel too.
> bench: send user a message for saves and deletes on broadcast page.

- utils/utils.go
- utils/utils_test.go
closes #257 
This is a ServeMux that extends the http.ServeMux to allow the provision of custom handler panic recovery. This was motivated by the desire to have notification on recovery of handler panics so that things don't fail so silently.
> Add RecoveryCallbackServeMux

- .gcloudignore
This was done because they were increasing the size of gcloud deployments.
> ignore .git and .github folders

- cmd/oceantv/broadcast/storage.go
This was done so we can stream to our youtube channel from our local machines.
> tv: check for youtube credentials env var in standalone

- cmd/oceantv/broadcast_manager.go
- cmd/oceantv/broadcast_states.go
- cmd/oceantv/broadcast_states_test.go
- cmd/oceantv/broadcast_test.go
When a ErrRequestLimitExceeded error is received from svc.CreateBroadcast we will use the disable on first failure bool in the failure closure to ensure the broadcast is disabled before making any additional calls to youtube (which will also be rate limited). This will prevent us from extending our broadcast down time by needlessly making blocked calls, adding to our rate limit.
closes #222
> TV: Use onFailureClosure for request limits (#222)

- cmd/oceanbench/s/broadcast.js
- cmd/oceanbench/t/broadcast.html
This was done because it was inconvenient to use the navigation menu then have to reselect a broadcast to refresh the selection.
> bench: add refresh button to broadcast page

- cmd/oceantv/broadcast_hardware_machine.go
This was done because the hsm was getting stuck and ignoring events that should have transitioned it.
Closes #278.
> tv: don't ignore stopping and starting request events

- cmd/oceantv/broadcast_states.go
- cmd/oceantv/main.go
The number of start failures was not being incremented correctly, meaning that broadcasts were not disabling after failing 3 times.
closes #231
> TV: Add back incrementing of failures (#231)

- cmd/oceantv/broadcast_hardware_machine.go
- cmd/oceantv/main.go
I noticed the hardware machine could get into a state of restarting but ignoring stop and start requests. Since it was ignoring start requests it never transitioned out of that state. Now it will transition, same for a stop request while restarting.
> tv: handle stop and start requests to prevent getting stuck in restarting

- cmd/oceantv/broadcast_machine.go
- cmd/oceantv/main.go
Closes #298 
It's possible through event emission that the current state transitions to something that does not implement particular interfaces we assert to, so now we're checking the success of these assertions in the methods that deal with checking if health, status or chat is due.
> Check success of state type assertions

- cmd/datablue/handlers.go
- cmd/oceanbench/admin.go
- cmd/oceanbench/main.go
- cmd/oceanbench/t/utils.html
Previously, if the site was changed on the utils page, it would resubmit the form. Since moving a device puts a variable, then deletes it, if the user switches to the site the device was moved to, it will delete the variables associated with that device.
This change also update the error reporting in datablue which can hide the root issue.
closes #288
> Ensure that utils form is not resubmitted (#288)

- cmd/oceanbench/admin.go
- cmd/oceanbench/api.go
- cmd/oceanbench/broadcast.go
- cmd/oceanbench/main.go
- cmd/oceanbench/monitor.go
- cmd/oceanbench/search.go
- cmd/oceanbench/set.go
- cmd/oceanbench/t/index.html
- cmd/oceanbench/ts/site-menu.ts
- cmd/oceanbench/video.go
- model/site.go
This change removes the need to call get sites before every page load, allowing the loading to happen completely async.
This should limit the number of database calls before returning the page to the user. This should make cloudblue feel like it loads slightly faster
> Bench: Use api/get/sites/user to populate site menu

- cmd/oceanbench/main.go
- cmd/oceanbench/set.go
- model/device.go
- system/rig_system.go
an endpoint has been added to /set/devices/new that reads the form fields for
- name
- mac
- wifi
- location
- device type and creates a new device based on these settings. At the moment the only supported device type is a controller.
> Bench: Add new device endpoint to create new device with defaults (#195)

- cmd/oceanbench/main.go
- cmd/oceanbench/s/index.js
- cmd/oceanbench/t/index.html
- cmd/oceanbench/ts/site-menu.ts
This change removes the unchecked reference to .Profile that was accidentally added in a previous change which was preventing logged out users from viewing the page.
This change also adds a spinner which gets replace by the number of sites, since the .User value was also removed.
> Bench: Remove unchecked reference to .Profile (#310)

- cmd/oceanbench/ts/header-group.ts
- cmd/oceanbench/ts/site-menu.ts
This change restores some features of the header group which were lost in a recent update. This includes:
- Defaulting to permission 1 for the nav menu for navigation before the site-menu has fully loaded
- Showing the current site name whilst the sites are loading
- Adding public sites to the site-selection
- Linking logotype to index
> Bench: Update Header for quality of life

- cmd/oceanbench/main.go
- cmd/oceanbench/monitor.go
- cmd/oceanbench/t/monitor.html
This change adds the last reported time to the monitor page for any devices that are not currently reporting (ie. red).
This change also sorts the monitor page so that the most recently reported devices are first in the list.
closes #281
> Bench: Add last reported time to monitor page (#281)

- cmd/oceanbench/main.go
- cmd/oceanbench/set.go
This change redirects any requests to /set/crons/* back to /set/crons/ on a call to writeCrons. This prevents resubmission of forms when changing sites.
closes #214
> Bench: Redirect all cron pages to base path (#214)

- cmd/oceantv/broadcast_hardware_machine.go
This is done to ensure that the hardware fully stops if requested to stop.
See issue #313.
> tv: ignore hardware start requests if stopping

- cmd/oceantv/main.go
- model/sensor.go
This function provides the latest transformed value for a sensor. This was motivated by the need for something like this in broadcast voltage handling.
> Add GetSensorValue

- cmd/oceantv/broadcast_hardware_machine.go
- cmd/oceantv/broadcast_machine_test.go
- cmd/oceantv/broadcast_manager_test.go
- cmd/oceantv/broadcast_states_test.go
- cmd/oceantv/broadcast_test.go
- cmd/oceantv/main.go
Depends on PR #327
This change extends the hardwareManager interface by adding voltage, alarmVoltage and isUp methods. These additions have been motivated by voltage handling in the broadcast functionality.
> Extend hardwareManager interface

- model/ausoceantv/feed.go
- model/ausoceantv/subscriber.go
- model/ausoceantv/subscription.go
This was done to get the basic entities in place for ausoceantv. They may change over time but that's okay.
> model: add ausoceantv entities

- cmd/oceanbench/api.go
- cmd/oceanbench/main.go
This change adds two endpoints to the API.
- /get/variables/site returns all of the variables for the site that are tied to a device.
- /get/devices/site returns all of the devices for a given site.
These changes allow us to make more async calls after a page has done an initial load.
> Bench: Add /get/devices/site and /get/variables/site endpoints (#113)

- cmd/oceanbench/s/cron.js
- cmd/oceanbench/t/set/cron.html
This changes allows the user to select from all of the variables on the site when setting a cron.
This also shows a human readable variable name, using the name of the device rather than the mac address. (the value is unchanged, and so all functionality is the same)
requires #321 
closes #113
> Bench: Use dropdowns for cron variables (#113)

- cmd/oceanbench/set.go
- system/options.go
- system/rig_system.go
This change generalises the options interface so that methods such as WithWifi can be reused for functions other than NewRigSystem.
The idea is that WithWifi can also be used in a NewPeripheral method in the future without needing to give it a different name, or putting it in another package.
Suggestions are appreciated, I am not sure if this is the best way of doing this.
> System: Generalise Options

- cmd/oceanbench/t/sandbox.html
- cmd/oceanbench/t/set/device.html
This was done so that necessary form values still submit values when greyed out. Closes #345 and closes #346 .
I tested on standalone to confirm fields are still greyed out and submit in the form.
> bench: change disabled form elements to readonly so they can be submitted

- cmd/ausoceantv/src/shared/global.d.ts
- cmd/ausoceantv/src/shared/tailwind.element.ts
- cmd/ausoceantv/src/shared/tailwind.global.css
This change adds support for tailwind styling in lit elements using the Vite Dev tools and PostCSS.
See #351 for a developer readme to explain how this works.
> AusOceanTV:Use tailwind with lit

- cmd/ausoceantv/.gitignore
- cmd/datablue/.gitignore
- cmd/oceanbench/.gitignore
- cmd/oceancenter/.gitignore
- cmd/oceancron/.gitignore
- cmd/oceantv/.gitignore
- model/.gitignore
This was done because my git status output was getting too big.
> Add gitignores for all modules/dirs that often contain generated files

- cmd/oceanbench/s/graph.js
Use the groupData field in the graph element, which limits the number of points that get rendered. This improves the render time.
**NOTE:** I tried the updated v5 of amcharts, but this actually performs worse and crashes on larger requests.
closes #263 
PS: There is possibly room to edit the group size to maximise performance vs usability
> Bench: Group Data in graph (#263)

- cmd/oceanbench/main.go
- oceanbench.yaml
This was done because we frequently experience latency and this could help speed things up.
> bench: add warmup requests and min_instances to bench for latency.

- cmd/oceanbench/main.go
- cmd/oceanbench/ts/site-menu.ts
This change now only alters the permission if none currently exists.
closes #364
> Bench: Fix site-menu public permissions (#364)

- cmd/ausoceantv/main.go
This change removes the service middleware which attached svc to ctx.locals, instead opting for member functions.
> AOTV: Remove service middleware in favour of member functions

- cmd/ausoceantv/.prettierrc
- cmd/ausoceantv/README.md
- cmd/ausoceantv/package-lock.json
- cmd/ausoceantv/package.json
This change adds prettier as a formatter to help keep formatting in sync.
This change adds a prettier setup to the project which will allow us to use consistent formatting guides.
The reason that I chose prettier is that it has a plugin for tailwind that will ensure that the classes will always be sorted the same, this benefits both the predictability of applying styles, but also makes it easier to make the classes consistent across commits.
See: https://tailwindcss.com/blog/automatic-class-sorting-with-prettier
> AOTV: Configure prettier (#372)

- cmd/ausoceantv/auth.go
- cmd/ausoceantv/index.html
- cmd/ausoceantv/src/types/user.ts
- cmd/ausoceantv/src/utils/context.ts
- cmd/ausoceantv/src/web-components/authenticator.ts
- cmd/ausoceantv/userauth.go
This change adds a custom element which wraps the page markup to get an authenticated user.
When the wrapper is loaded, it fetches the profile from the ```/api/v1/auth/profile``` endpoint. This then provides a user-context to other elements in the tree.
Inspired by user-provider from openfish.
> AOTV: Add authenticator wrapper around contents.

- cmd/ausoceantv/src/types/user.ts
This was done because typescript wouldn't let us run npm run build without it.
> ausoceantv: initialise user.name to empty string

- cmd/oceanbench/s/configure.js
- cmd/oceanbench/set.go
This change fixes the nav menu by ensuring the common data Page field is initialised correctly. This change also adds field validation for the configure page.
closes #344
> Bench: Fix Navmenu on configure page (#344)

- cmd/oceanbench/main.go
- cmd/oceanbench/t/set/device.html
This change restores the name="ct" attribute to the client type field on the devices page. This was otherwise meaning that the type was getting overwritten as an empty string.
> Bench: add name to type input field

- cmd/oceanbench/set.go
- cmd/oceanbench/t/configure.html
- cmd/oceanbench/t/sandbox.html
- cmd/oceanbench/t/set/device.html
This change adds links back to the /set/devices page from the auto configuration pages.
This allows other devices to still be setup on the sandbox page whilst they aren't yet implemented.
> Bench: Hide autoconfig

- go.mod
- go.sum
- model/feed.go
- model/model_test.go
- model/subscriber.go
- model/subscription.go
- utils/utils.go
This change implements the methods required for getting, creating and updating subscribers and subscriptions.
Also adds tests for the methods.
See the schema doc for details on these methods and types: https://docs.google.com/document/d/12TYm5Al0G3T-R0wiWtX7-vrB0Yn5dH8VYRo8yWTujjY/edit?tab=t.0#heading=h.mj06vfrpcpf5
requires #387
> model: Add methods for subscription and subscriber (#391)

- cmd/oceantv/broadcast_events.go
- cmd/oceantv/broadcast_machine.go
- cmd/oceantv/broadcast_machine_test.go
- cmd/oceantv/broadcast_states.go
- cmd/oceantv/broadcast_states_test.go
Resolves issue #359 
Up until this point, critical failures i.e. those that cause repeated broadcast failure, have resulted in disabling of the broadcast. Unfortunately, this meant that any stored events at the time of disabling would not get processed, such as hardware shutdown requests. This is because the state machines of disabled broadcasts do not spin up.
Furthermore, there should probably be a differentiation between a broadcast that is in a critical failure state, as opposed to one that is just inactive.
For the aforementioned reasons, this commit changes the behaviour of the broadcast state machine when it struggles to start a broadcast. If we exceed the allocated number of attempts, then a critical failure event is emitted. In response to this event, the broadcasts will move to …
> Go to failure state instead of disabling broadcast

- cmd/oceantv/broadcast_hardware_machine.go
This was done because I don't think the AlarmVoltage was being retrieved properly. There was no reference to the device.
I also added a print for save hardware state because we see an error about this all the time and it would be good to have more logging.
> tv: correct alarm voltage variable name

- cmd/oceanbench/broadcast.go
This was done because the scheduler wont check the datastore often, only when the oceancron service starts.
Addresses issue #406
> bench: set broadcast check cron in scheduler after putting it in the datastore

- cmd/oceanbench/broadcast.go
- cmd/oceanbench/main.go
This change adds a form value ?embed to the /live endpoint which allows the user to specify if they want an embedable link for a youtube iFrame.
closes #400
> Bench: Provide embed redirect link (#400)

- cmd/ausoceantv/main.go
- cmd/ausoceantv/stripe.go
- model/subscription.go
This change adds 2 new endpoints, ```/get/subscription``` and ```/stripe/cancel```. These will allow the front-end to get data about the subscription and cancel the subscription respectively.
> AOTV: Add endpoints for subscriptions

- cmd/ausoceantv/main.go
- cmd/ausoceantv/plans.html
This change adds a priceID query parameter to the links from the plans page to the checkout. This will allow for the checkout to determine which product is being purchased.
These priceIDs come from stripe, and will need to be updated if the products ever get changed. We could potentially think about making these be loaded via an API call to make sure they are always up to date, but I think this works for now.
> AOTV: Add priceID to checkout links from plans (#383)

- cmd/ausoceantv/main.go
- model/model_test.go
- model/subscriber.go
This changes the key of the subscriber from a 10 digit ID to a concatenation of the ID and the email.
This was done so that the entity could be queried by email by the filestore.
> Model: Use namekey for subscriber

- cmd/ausoceantv/package.json
- cmd/oceanbench/package.json
- deploy.sh
- oceanbench.yaml
This change adds a deploy.sh script which can be called from a cmd/ directory to build and deploy a service. This script can deploy to either a development mode (dev-dot-...) or to the most recent version (scraped from main.go version) with the version being promoted.
This script has been added to npm run deploy and deploy:dev for both ausoceantv and oceanbench.
> Add deployment script for cloud projects

- cmd/oceantv/broadcast_events.go
- cmd/oceantv/broadcast_events_test.go
- cmd/oceantv/broadcast_hardware_machine.go
- cmd/oceantv/main.go
- cmd/oceantv/registry/map.go
- cmd/oceantv/registry/registry.go
- cmd/oceantv/registry/registry_test.go
- cmd/oceantv/system.go
The current pattern of adding an event or state type and then adding to
the stringTo function map was error prone and clunky. By using a
registry we can register events immediately, which is much more
intuitive and clear. The stringTo functions then just uses the registry
to retrieve an event of the provided type.
The registry employs a singleton i.e. the registry is only ever
instantiated once, and cannot be externally re-instantiated or
replaced.
> oceantv: register events and states using registry

- cmd/oceanbench/.prettierrc
- cmd/oceanbench/package-lock.json
- cmd/oceanbench/package.json
- cmd/oceanbench/s/download.html
- cmd/oceanbench/s/player/audio-player.html
- cmd/oceanbench/s/player/audio/index.html
- cmd/oceanbench/t/admin.html
- cmd/oceanbench/t/broadcast.html
- cmd/oceanbench/t/configure.html
- cmd/oceanbench/t/cron-index.html
- cmd/oceanbench/t/footer.html
- cmd/oceanbench/t/index.html
- cmd/oceanbench/t/monitor.html
- cmd/oceanbench/t/mooring.html
- cmd/oceanbench/t/play.html
- cmd/oceanbench/t/register.html
- cmd/oceanbench/t/sandbox.html
- cmd/oceanbench/t/search.html
- cmd/oceanbench/t/set/cron.html
- cmd/oceanbench/t/set/device.html
- cmd/oceanbench/t/upload.html
- cmd/oceanbench/t/utils.html
For a long time our html format hasn't been consistent or checked. 
Running prettier with npm run format should help us keep our html formatting consistent. 
This change is the initial output from prettier.
I tested that bench compiles and the templates parse and the pages all look right.
> bench: use prettier to format our html

- cmd/oceanbench/broadcast.go
- cmd/oceanbench/main.go
- cmd/oceanbench/t/broadcast.html
- cmd/oceantv/broadcast.go
- cmd/oceantv/broadcast_events.go
- cmd/oceantv/broadcast_hardware_machine.go
- cmd/oceantv/broadcast_hardware_machine_test.go
- cmd/oceantv/broadcast_machine_test.go
- cmd/oceantv/broadcast_manager_test.go
- cmd/oceantv/broadcast_test.go
- cmd/oceantv/main.go
- go.mod
Closes issue #31 
We would like to start doing a proper shutdown to power down the cameras as opposed to just cutting the power. To do this we have decided to have two substates in the stopping state i.e. shutdown and power off.
Another change that has resulted is that the restart state actually has substates i.e. stopping and starting.
These changes have resulted in a cascade of changes especially to testing.
> oceantv: split stopping state into shutdown and power off

- cmd/oceanbench/data.go
- cmd/oceanbench/main.go
- cmd/oceanbench/monitor.go
- cmd/oceanbench/s/graph.js
- cmd/oceanbench/search.go
This is useful to see throughput characteristics over time.
We're doing this by adding a quasi-pin i.e. it's not a real sensor pin, but we can set the pin to "throughput" on the UI for the device, and then have special handling of this case to use the throughputs endpoint which gets historical data to provide for graphing. The process is very similar to the data endpoint handling however, the datastore ops are different to get the data.
> bench: add device throughput graphing

- cmd/oceanbench/main.go
- cmd/oceanbench/search.go
This change uses the sensor names for a pin when they exist on the search page.
> Bench: Use sensor names when available

- cmd/ausoceantv/.prettierrc
- cmd/ausoceantv/package.json
- cmd/ausoceantv/src/types/user.ts
This was done to be consistent across projects.
> ausoceantv: match bench prettier config and run

- cmd/oceanbench/broadcast.go
This was done since broadcasts could not be created as the hardware state could not be found in the datastore.
> Bench: Assume newly created broadcast on failed to find.

- cmd/oceantv/broadcast.go
- cmd/oceantv/broadcast_manager.go
- cmd/oceantv/main.go
- cmd/oceantv/store.go
- cmd/oceantv/utils.go
Closes issue #360 
It's awkward to need to provide a different datastore based on the entity kind, and is also error prone. We're trying to improve this situation by creating a "facade" datastore, CompositeStore, which selects the appropriate datastore instance based on the kind.
> oceantv: add and use composite store

- cmd/ausoceantv/main.go
This was done because logging out and other requests would cause an error, header fields too large.
> ausoceantv: increase readbuffersize for http headers

- cmd/oceanbench/broadcast.go
- cmd/oceanbench/main.go
This was done to support a more customised experience on AusOceanTV with embedded live streams.
> bench: add live redirect options for mute, autoplay, related 

- .gcloudignore
- cmd/oceantv/.gitignore
Added node modules in new ausoceantv/webapp folder to the gcloud ignore file as well as the youtube-api-credentials.json file in the oceantv folder which gets copied there from time to time.
> update gcloud ignored

- cmd/oceanbench/main.go
- cmd/oceanbench/monitor.go
- cmd/oceanbench/t/monitor.html
This change allows a user to easily click through to search a given sensor, saving a number of form submissions to achieve the same result otherwise.
> Bench: Add search shortcut to monitor page.

- cmd/ausoceantv/auth.go
- cmd/ausoceantv/dsclient/dsclient.go
- cmd/ausoceantv/main.go
- cmd/ausoceantv/stripe.go
- cmd/oceanbench/auth.go
- gauth/userauth.go
- model/subscriber.go
This was reverted so that we have subscriber info from the point of login. This was we can do things based on the _Created_ field etc.
It was originally this way, but it was changed due to issues getting the token right away so it was moved, but David and I agree that it should be here so I have made it so that we can access the profile and token right away.
I also realised that we were using the netreceiver datastore, which will be deprecated, so I have changed it to vidgrind.
The subscriber is still checked at checkout but not created.
> ausoceantv: create a subscriber on login not checkout

- cmd/oceanbench/broadcast.go
- cmd/oceanbench/main.go
- cmd/oceanbench/t/broadcast.html
- cmd/oceantv/broadcast.go
- cmd/oceantv/broadcast_manager.go
- cmd/oceantv/broadcast_service.go
- cmd/oceantv/broadcast_test.go
- cmd/oceantv/main.go
This will allow us to broadcast live with unlisted privacy, but then on completion, set to public. This means we can restrict live viewing to the AusOceanTV platform, but still have past broadcasts on the YouTube channel.
> Set privacy on broadcast completion

- cmd/ausoceantv/auth.go
- cmd/oceanbench/auth.go
- gauth/userauth.go
This change handles errors passed to the callback and wraps them with an error so they can be more easily parsed and handled properly by the server.
closes #462
> gauth: Handle errors in callback url (#462)

- cmd/ausoceantv/main.go
- cmd/oceanbench/main.go
- cmd/oceanbench/sandbox.go
- cmd/oceanbench/set.go
- cmd/oceanbench/t/configure.html
- cmd/oceanbench/t/sandbox.html
- cmd/oceanbench/t/set/device.html
- cmd/oceanbench/ts/site-menu.ts
- system/rig_system.go
- system/rig_system_test.go
This change adds a new endpoint /sandbox for the sandbox site which users are automatically redirected to.
This also fixes a few small bugs with the config process, such as loosing the device key upon configuration.
closes #309
> Bench: Add unique sandbox endpoint (#309)

- cmd/ausoceantv/main.go
- cmd/ausoceantv/stripe.go
- utils/utils.go
This change creates a new endpoint that stripe will send events to.
The events that we currently handle are payment_intent.succeeded, and invoice_payment.succeeded which will tell us when payments are successful for one off and subscriptions respectively.
This will help us stay up to date with the stripe database.
closes #421
> AOTV: Handle stripe webhooks (#421)

- cmd/oceantv/main.go
- cmd/oceantv/store.go
This change adds some missing kinds to the ausocean composite store factory. We're also wrapping the store get process so that we can have better panic messaging if the mapping doesn't exist.
> otv: fix composite store missing kinds

- go.mod
- notify/notify.go
The new HTMLEmailer interface is for types which can send emails using formatted HTML.
This change implements a simple method for a MailjetNotifier.
This is a really basic change that should allow us to send basic emails to ausoceantv users, but we may want to explore how we can use the mailjet platform for more refined and complex emails. Especially since email html != web html.
We could also just add the type of email as an option to the existing send method, since there is a lot of overlap in the code, but I'm not sure that its a good abstraction. I think that having the seperate interface can be useful for other services as well, since the notifier up until now has been very clearly designed for purpose (being site and broadcast notifications), without much generality in mind. I think …
> Notify: Add new HTMLEmailer interface

- cmd/ausoceantv/main.go
- cmd/ausoceantv/stripe.go
- cmd/ausoceantv/webapp/src/web-components/profile-details.ts
This change update the subscription on the stripe server to make sure that we are in sync when cancelling to avoid users getting charged when it seemed like they had cancelled the subscription.
This change also adds a few checks and conditional rendering in the profile-details element to make it easier to see the state of the subscription.
> AOTV: Update stripe subscription to cancel (#420)

- cmd/oceanbench/main.go
- cmd/oceanbench/t/admin.html
This change prevents the site-menu from reloading and resubmitting the form for the site admin page.
closes #441
> Bench: Prevent form resubmission on admin page (#441)

- cmd/oceanbench/broadcast.go
- cmd/oceanbench/t/broadcast.html
- cmd/oceantv/broadcast.go
- cmd/oceantv/broadcast_hardware_machine.go
- cmd/oceantv/main.go
Make battery voltage pin configurable and default to the ESP32 A4 pin when it's not defined in the broadcast config.
> otv: update battery voltage pin

- cmd/ausoceantv/main.go
This change defaults the error message from the logAndReturnError function to be the status text of the response status code, which by default is internal server error.
This should make the default response to the user to be more understable, or at least not make the UI look buggy with excessive error printing.
> AOTV: Default error message to status text

- model/factories.go
- system/rig_system.go
This change adds the battery voltage sensor for the ESP32 which will be added by default to the config
> Bench: Add battery voltage for esp32

- cmd/ausoceantv/auth.go
We can't create a stripe customer in lite mode since we don't have production keys.
> AOTV: Don't create stripe customer in lite mode

- cmd/oceantv/broadcast_hardware_machine.go
- cmd/oceantv/broadcast_hardware_machine_test.go
- cmd/oceantv/main.go
Because the nested states use substates of interface state, we need to add custom marshaling/unmarshaling to deal with this.
> otv: add custom marshalling for nested hardware states

- cmd/ausoceantv/webapp/index.html
This was done so that existing users don't feel like they have to sign up again.
> ausoceantv: login link under sign up

- cmd/oceanbench/broadcast.go
- cmd/oceanbench/main.go
This fixes the error where there are no shutdown actions for a broadcast since they just aren't being read.
> Bench: Parse Shutdown Actions

- cmd/oceantv/main.go
This change ensures that only fields that are actually set by the broadcasting UI are actually saved to the config. This should prevent state data from being overwritten.
> OTV: Use better update function on initial broadcast save (#315)

- backend/handler.go
This change allows users of the Handler interface to access cookies on the requests.
> Backend: Add Cookie method to Handler

- cmd/ausoceantv/main.go
- gauth/userauth.go
There's no way of getting another refresh token if it's gone for some reason (user clears cookies), so we need to check and prompt for consent if it's missing to get another refresh token. Unless we decide we want to store the refresh tokens in our DB.
> cmd/ausoceantv: if there is no refresh token, prompt consent

- cmd/oceanbench/broadcast.go
- cmd/oceantv/main.go
This change makes sure we only create the broadcastCheck cron if it doesn't exist already. This ensures that if we've modified the broadcast check cron to hit the testing endpoint we don't overwrite that whenever we save the broadcast config.
> bench: only add broadcast cron when doesn't exist

- cmd/oceantv/broadcast/youtube.go
- cmd/oceantv/broadcast_states.go
- cmd/oceantv/main.go
- cmd/oceantv/system.go
Occasionally we were getting into a situation where a broadcast would be disabled but the YouTube broadcast object would still be broadcasting. This ensures this doesn't happen by checking that there are no live broadcast YouTube objects associated.
> otv: check there's no YouTube broadcast if not enabled

- cmd/oceantv/broadcast.go
- cmd/oceantv/broadcast_events.go
- cmd/oceantv/broadcast_machine.go
- cmd/oceantv/broadcast_machine_test.go
- cmd/oceantv/broadcast_manager.go
- cmd/oceantv/broadcast_states.go
- cmd/oceantv/main.go
- cmd/oceantv/system.go
This change provides the option to add event or state based webhooks (or any other sort of hook for that matter). This is is motivated by the desire for services such as AusOceanTV and OpenFish to have an awareness of broadcast events and states.
We have done this by using options to an oceantv service, which then propagates these hooks to the state machine.
closes #526
> otv: enable state/event based webhooks

- cmd/oceantv/broadcast_events.go
- cmd/oceantv/broadcast_machine.go
- cmd/oceantv/broadcast_states.go
- cmd/oceantv/broadcast_states_test.go
- cmd/oceantv/main.go
This allows us to know why we're in the direct failure state in the first place.
> otv: store error in directFailure state

- model/entities.go
- model/model_test.go
- model/subfeed.go
Add methods and testing for subfeed methods.
> Model subfeed methods

- cmd/oceantv/broadcast_events.go
- cmd/oceantv/broadcast_hardware_machine.go
- cmd/oceantv/broadcast_hardware_machine_test.go
- cmd/oceantv/broadcast_machine.go
- cmd/oceantv/broadcast_machine_test.go
- cmd/oceantv/broadcast_states.go
- cmd/oceantv/broadcast_test.go
- cmd/oceantv/main.go
- cmd/oceantv/system.go
The intention here is to improve the function of events that represent erroneous conditions and make error information more available and clearer. We're also trying to use more consistent patterns around error conditions, and do more central notification on these error events.
Events representing erroneous conditions are errors themselves. They also hold errors instead of basic strings. This means we can chain error events/errors and maintain a history of the errors that led us to where we are. As such we have unwrapping functionality to find the initial error event type. We've also added a Kind() method to the interface that gives us the corresponding notify.Kind so that we can perform a notification of the correct kind.
Finally we've fixed some fundemental issues around storing events …
> otv: improve error event handling

- .gcloudignore
- cmd/oceanbench/data_test.go
This was done so that the test wouldn't panic when it fails. It's still unclear why it failed and is now passing.
Fixes the panic in issue #542
> bench: fix TestGetScalars panic

- cmd/oceantv/broadcast_events.go
- cmd/oceantv/broadcast_events_test.go
- cmd/oceantv/broadcast_hardware_machine.go
- cmd/oceantv/main.go
- cmd/oceantv/system.go
Events are complex in that they can be of errorEvent type which means that they can chain other errorEvents or normal errors.
This change fixes error matching using Is and marshalling/unmarshalling so that it happen recursively and reconstruct the events exactly as they were. We've also added testing to verify things are working as expected.
> otv: fix event marshalling/unmarshalling and error matching

- cmd/oceanbench/broadcast.go
- cmd/oceanbench/main.go
- cmd/oceanbench/t/broadcast.html
- cmd/oceantv/broadcast.go
- cmd/oceantv/main.go
- cmd/oceantv/system.go
This allows us to add notification rules through the broadcast page. This means we can suppress notifications of a particular kind or containing a particular string. The rules are in a JSON format: { "SuppressKinds" : ["kind1","kind2", ... ], "SuppressContaining": ["some str"] }
> otv & bench: add notification suppression rules

- cmd/oceantv/broadcast_hardware_machine.go
- cmd/oceantv/main.go
When we have a low voltage case, the ESP goes into alarm mode, but then there will be no voltage sensor value. So if we get a no such entity error, we assume the voltage is the alarm voltage.
> otv: handle no voltage value when ESP off

- cmd/datablue/handlers.go
- cmd/datablue/main.go
This is a simple mechanism for clients that lack accurate timers or access to network time to  to keep the time, albeit approximately.
> Return timestamp (ts) with config response

- cmd/datablue/handlers.go
- cmd/datablue/main.go
Now that the ESP NetSender client always requests vars upon restart, it is useful to include the request code (rc) and timestamp (ts) in the response, as we do for config requests.
> vars response now includes rc and ts

- cmd/oceantv/broadcast_hardware_machine.go
- cmd/oceantv/broadcast_machine.go
- cmd/oceantv/main.go
In the hardwareStopping state, if the poweringOff substate fails a hardwarePowerOffFailedEvent is emitted, but we weren't handling this. We need to handling this in the hardwareStopping state and then transition to hardwareFailed.
> otv: add missing event handling for powerOffFailedEvent

- cmd/oceanbench/broadcast.go
- cmd/oceanbench/main.go
- cmd/oceanbench/t/broadcast.html
- cmd/oceantv/main.go
This change adds a reset state button to the broadcast UI which will allow the user to reset the state of a broadcast without breaking any other values.
closes #582
> Bench: Add reset button (#582)

- cmd/oceanbench/t/search.html
This change extends the length of the select element on the search page to make longer device names easier to read.
> Bench: Search Longer Device Names (#567)

- cmd/oceanbench/main.go
- cmd/oceanbench/set.go
- cmd/oceanbench/t/set/device.html
- docs/oceanbench/device-configuration.md
This change adds the auto-calibration functionality to the alarm variable. This calibrates the alarm voltage, and alarm recovery voltage whenever the battery voltage is calibrated.
This also fixes an error, where calibrating voltages that are reading 0 returns an inf, or NaN result.
> Bench: Add calibration for alarm var

- cmd/upload/main.go
- youtube/upload.go
Also added cmd for local upload to AusOcean YouTube
> youtube: add function to upload video to AusOcean YouTube

- exp/uploader/main.go
- exp/uploader/t/upload.html
It's useful to have a description associated with uploaded media. The description is written to a separate bucket object named `FILENAME.txt,` where `FILENAME` is the name of the bucket object holding the media data.
> Added description

- cmd/oceanbench/search.go
- cmd/oceanbench/t/search.html
This was done for testing/debugging GPS and NMEA sentence searching.
It does basic formatting, and provides the raw text to view and download. 
Closes #629 
(I also tested that viewing logs still works)
> bench/t/search: render GPS / NMEA text
