cmd/oceancron/cron.go, cmd/oceancron/cron_test.go
Moved cron_test.go here from VidGrind.
=> Add cron tests

cmd/oceancron/cron.go, cmd/oceancron/cron_test.go, gauth/secrets_test.go
Added some extra tests to both gauth and OceanCron.
=> More tests

cmd/oceantv/broadcast.go
Use Sensor.Pin properly and remove redundant float64 typecast.
=> Use Sensor.Pin properly

cmd/oceantv/broadcast_hardware_machine.go
A minor improvement to some logging
=> Log when checking revidCameraClient status

cmd/oceanbench/main.go
=> Serve templates from "t" directory in standalone mode

cmd/oceanbench/text.go
=> Deprecate use of BinaryData for storing text

cmd/datablue/handlers.go, cmd/oceanbench/s/main.js, cmd/oceanbench/search.go, model/binary.go, model/mtsmedia.go
=> Port binary data

notify/notify.go, notify/notify_test.go, notify/options.go
=> Support for multiple recipients

cmd/oceancron/cron.go
The http req was previously created outside the action func. Moving it inside is probably safer.
=> Move http request creation inside rpc action func

cmd/oceanbench/broadcast.go, cmd/oceanbench/s/broadcast.js, cmd/oceanbench/t/broadcast.html, cmd/oceantv/broadcast.go
This was done because it was requested in another PR but I thought it deserved its own PR to not muddle things up.
=> bench,tv: change StartTimeUnix to StartTimestamp ditto for end

cmd/oceantv/broadcast/auth.go
This change uses a global variable to handle the ytcredscallback endpoint, and is set during each call to genToken. This prevents pattern matching duplication. 
Also change the scheme of the redirect to use http not https if running on localhost.
=> TV: Use variable function for callback handling (#163)

cmd/oceantv/broadcast_machine.go, cmd/oceantv/broadcast_states.go
Depends on #179 
We recently introduced this nice wrapper for log and email notification. We're now using this more extensively to reduce boiler plate.
=> Use logAndNotify function

cmd/oceantv/broadcast_machine.go, cmd/oceantv/broadcast_states.go, cmd/oceantv/utils.go, cmd/oceantv/utils_test.go
Depends on #180 
We have a common pattern where we try a call and if not successful we log. We're factoring this out into a convenience function that wraps this.
=> Add convenience try function to reduce boilerplate

cmd/oceantv/broadcast_machine.go, cmd/oceantv/broadcast_states.go
We're increasing the specificity of notifications by having the kind being passed into the logAndNotify method.
We've also introduced a kind enum with values relevant to broadcasting we can use across the oceantv functionality.
=> Use notify.Kind in logAndNotify

notify/notify.go, notify/notify_test.go, notify/options.go
This makes it possible to customize notification recipients by site key and/or notification kind.
=> Added WithRecipientLookup option

cmd/oceanbench/broadcast.go
When the broadcast save action is called we will get the previously associated account for the broadcast and update the current config with that value to prevent users from changing this. The value can only be changed when the generate-token action is called. We will also not parse the value from the form to ensure this value can "never" be leaked through.
closes #155
=> Bench: Prevent Changing of Youtube Channel (#155)

cmd/oceanbench/main.go, cmd/oceancenter/main.go, cmd/oceancron/main.go, cmd/oceantv/main.go, go.mod, notify/notify.go, notify/notify_test.go, notify/options.go, notify/timestore.go, oceanbench.yaml, oceancron.yaml, oceantv.yaml
but specified either by WithPeriod or a WithRecipientLookup function.
=> Notification period is no longer part of the TimeStore

model/actuator.go, model/device.go, model/factories.go
This change implements factories for the following actuators.
- Device 1 -> Power 1
- Device 2 -> Power 2
- Device 3 -> Power 3
=> Model: Add actuator factories (#206)

system/rig_system.go, system/rig_system_test.go
NewControllerSystem returns a controller system based on the passed inputs and functional options. The ControllerSystem is used to link together a controller device, its variables, sensors, actuators, and eventually connected peripherals.
See also: #207 #209 #210
=> System: Add NewControllerSystem

cmd/oceanbench/broadcast.go, cmd/oceanbench/main.go, cmd/oceanbench/t/broadcast.html
This was done to prevent crashing on nil Sites for broadcasts on broadcast.html.
Closes Issue #250
=> bench: check site in broadcast.html exists, return after GetSite error

notify/notify.go
Depends on #258 
This is intended to be a bare-bones email send function i.e. it doesn't deal with filters and categorisation based on site and kind like the MailjetNotifier implementation offers.
It's intended to be used for critial notification e.g. panic recovery.
=> Add Send to notify package

cmd/oceancron/cron_test.go, model/factories.go, model/model_test.go, model/sensor_test.go
Also fixed a few string conversions in factories.go.
=> Fixed tests

cmd/oceantv/main.go
depends on #259 
This change updates oceantv to use the RecoveryCallbackServeMux. This means that on handler panic we no longer use the default recovery mechanism, which is relatively quiet, and instead now use a bare-bones email notification to make it clear that a panic has occured during serving.
=> Utilise RecoveryCallbackServeMux in oceantv

model/actuator.go, model/factories.go, model/sensor.go, system/rig_system.go, system/rig_system_test.go
The following functional options have been added to the system layer:
- WithVariables
- WithSensors
- WithActuators
- WithPeripherals
This change also switches factories to all return pointers.
=> System: Add RigSystem Options and Testing (#195)

cmd/oceancenter/main.go
=> Use space as config delimiter

cmd/oceanbench/main.go, cmd/oceanbench/set.go, cmd/oceancenter/main.go
=> Automatic site selection for device settings

cmd/oceantv/main.go
Only notify YouTubeEmail for hardware, network, and configuration issues.
=> Limit YouTubeEmail notifications

model/device.go, system/rig_system.go
The followig options were added:
- WithDefaults
- WithWifi
- WithLocation
Acutators and sensors now add to the input and output list of the controller.
=> system: More Options and add IO automatically (#195)

cmd/oceanbench/main.go, cmd/oceanbench/set.go, cmd/oceanbench/t/sandbox.html, model/device.go, model/site.go, system/rig_system.go
This change alters the default devices page for the sandbox site, tailoring the experience towards new device configuring.
requires #302
=> Bench: Add unique devices page for sandbbox site

cmd/oceanbench/filter.go, cmd/oceanbench/main.go, cmd/oceanbench/s/play.js
This change tracks the source and current state of the audiofile throughout the lifecycle of the page. This ensures that the type of the file, and its source is correct, so that filters can be properly applied
=> Bench: Fix Audio Filters (#308)

cmd/oceanbench/monitor.go, cmd/oceantv/broadcast.go, cmd/oceantv/broadcast_manager.go, cmd/oceantv/main.go, model/scalar.go
This was used in several places, so it made sense to generalise it. This will also be used for the broadcast voltage handling.
=> Add GetLatestScalar to model package

cmd/oceanbench/main.go, cmd/oceanbench/t/set/device.html
This changes updates the device page UI, making it better match the rest of the UI, as well as hiding some of the advanced features that most users don't need to see. This changes also makes the page work better on mobile.
=> Bench: Update Device page UI

notify/notify.go
=> Pass recipients to send, not n.recipients

cmd/ausoceantv/package-lock.json, cmd/ausoceantv/package.json, cmd/ausoceantv/postcss.config.js, cmd/ausoceantv/src/index.css, cmd/ausoceantv/tailwind.config.js
This change adds tailwindcss configuration.
Tailwind works really well with the Vite developer tools as well, and requires no additional scripts to run.
=> Ausocean TV: Add tailwind to Frontend setup

cmd/oceanbench/s/graph.js
This change makes graphing requests batched and sent all at once, rather than sending them serially and waiting for a response before sending the next request.
This improves graphing time significantly.
TODO: This change does not change the resolution of the request, and so rendering the results can still take a long time. To make the rendering faster you must still request a lower resolution manually. It is proposed to use some form of algorithm (either on the frontend or backend) to automatically determine a reasonable resolution and only graph that many points.
Addresses #263
=> Bench: Pipeline requests for faster graphing (#263)

cmd/ausoceantv/README.md
This readme should help developers with some of the project specific technologies used in the development of AusOcean TV.
Describes #350
=> AusOceanTV: Add Developer README

cmd/ausoceantv/package-lock.json, cmd/ausoceantv/package.json
This wasn't added for a previous change when it should have been.
=> ausoceantv: upate package.json for lit/context

cmd/ausoceantv/home.html, cmd/ausoceantv/src/web-components/authenticator.ts, cmd/ausoceantv/watch.html
This change adds a logout button to the home page.
This change also redirects users from any page to the index page if they are not signed in.
=> AOTV: Add buttons for auth methods

cmd/ausoceantv/auth.go, cmd/ausoceantv/index.html, cmd/ausoceantv/main.go
This change checks the profile of a users request to login. If the profile exists, the user is redirected to the target query parameter stated in the URL.
Closes #378
=> AOTV: Prevent users from re-signing in (#378)

cmd/oceanbench/s/configure.js
This change updates the configure.js which should have been used originally but was missed.
This is the original configure.js file, which was missed in the original commit. (replaces the temporary file used in the last commit)
=> Bench: Update configure.js

go.mod, go.sum, model/subscriber.go, utils/utils.go
This change adds the CreateSubscriber method, and the GetSubscriberByEmail methods.
=> Model: Add subscriber create and get methods (#385)

cmd/ausoceantv/auth.go, cmd/ausoceantv/main.go, go.mod, go.sum, model/subscriber.go, utils/utils.go
When a new user signs in, check if there is an existing subscriber with the given email otherwise create a new subscriber.
closes #385
=> AOTV: Create new subscriber on signin (#385)

cmd/ausoceantv/main.go, cmd/ausoceantv/stripe.go
This change adds proper support for stripe subscriptions, as well as keeping support for once off purchases.
Requires #413
=> AOTV: Support Stripe Subscriptions (#383)

ausoceantv.yaml, cmd/ausoceantv/auth.go, cmd/ausoceantv/index.html, cmd/ausoceantv/main.go, cmd/ausoceantv/stripe.go, cmd/ausoceantv/vite.config.ts
This change adds a new development environment variable so that the correct stripe key is used in testing deployments.
Additionally links have been updated to point towards .html files.
=> AOTV: Make deployable

cmd/ausoceantv/checkout.html, cmd/ausoceantv/main.go, cmd/ausoceantv/src/checkout.css, cmd/ausoceantv/src/checkout.js, cmd/ausoceantv/stripe.go
This change adds the current cart to the checkout page such that the user can see what they are purchasing.
requires #414 
closes #383
=> AOTV: Add cart info to checkout page.

ausoceantv.yaml, cmd/ausoceantv/main.go, cmd/ausoceantv/webapp/package.json, cmd/oceanbench/package.json, scripts/deploy.sh
This was done after moving the web files into a webapp folder.
I also put the deploy.sh script in scripts where it belongs.
I also added a LITE environment variable so that we can deploy to the production version without stripe keys etc.
=> aotv: make aotv deployable again

go.mod, model/model_test.go, model/subscriber.go, model/subscription.go
This change updates some of the handling and indexing for subscriber and subscription functions.
=> Model: Update subscriber and subscription functions

cmd/ausoceantv/main.go, cmd/ausoceantv/webapp/policies/privacy.html, cmd/ausoceantv/webapp/policies/terms-of-service.html, cmd/ausoceantv/webapp/tailwind.config.js
This change adds a terms of service and privacy policy to the site. They have been formatted to match the site formatting.
Due to HTML formatting ordered lists weird, I have used a table instead to make sure that the indices are aligned how we want them.
=> AOTV: Terms of Service and Privacy Policy

cmd/ausoceantv/auth.go, cmd/ausoceantv/main.go, cmd/ausoceantv/stripe.go, cmd/ausoceantv/webapp/src/survey-check.ts, cmd/ausoceantv/webapp/src/survey.ts, cmd/ausoceantv/webapp/src/web-components/authenticator.ts, cmd/ausoceantv/webapp/src/web-components/profile-details.ts
This change adds a simple helper function which can log an error, as well as return an error using properly formatted JSON.
Callers can set a different value to be returned to the frontend, as well as specifying the response code through functional options.
=> AOTV: Add logAndReturnError function (#474)

cmd/ausoceantv/auth.go, cmd/ausoceantv/main.go
This change creates a stripe customer when a new user signs in, this should give us more functionality with access to the customers via stripe.
closes #479
=> AOTV: Create customer with subscriber (#479)

cmd/ausoceantv/main.go, cmd/ausoceantv/webapp/src/survey.ts, cmd/ausoceantv/webapp/survey.html
This was done so that we're always capturing the location data despite the possibility of not including the post code in the input.
After this PR we will create an Entity that stores the geocode instead of the JSON being stored in the subscriber. This is just a step in the right direction.
=> ausoceantv: use geocode instead of postcode and city

cmd/ausoceantv/main.go, cmd/ausoceantv/webapp/src/survey.ts, cmd/ausoceantv/webapp/survey.html, model/entities.go, model/region.go, model/subscriberregion.go
This was done so that the location (region) data is query-able in the datastore.
=> ausoceantv: make SubscriberRegion entity, methods and use it in the survey

cmd/ausoceantv/webapp/plans.html, cmd/ausoceantv/webapp/src/plan-element.ts
This change updates the styling of the plans page to make it up to date with the rest of the servive.
=> AOTV: Update plans styling

cmd/ausoceantv/stripe.go, cmd/ausoceantv/webapp/checkout.html, cmd/ausoceantv/webapp/src/checkout.js
This change checks if a user has a current subscription before returning a payment intent which would allow them to create a new subscription.
This change also handles the errors better in the frontend by redirecting the user depending on the error.
=> AOTV: Prevent multiple subscriptions (#482)

cmd/ausoceantv/main.go, cmd/ausoceantv/webapp/checkout.html, cmd/ausoceantv/webapp/home.html, cmd/ausoceantv/webapp/index.html, cmd/ausoceantv/webapp/plans.html, cmd/ausoceantv/webapp/policies/privacy.html, cmd/ausoceantv/webapp/policies/terms-of-service.html, cmd/ausoceantv/webapp/profile.html, cmd/ausoceantv/webapp/survey.html, cmd/ausoceantv/webapp/watch.html
This change adds the google analytics script to each of the html pages to enable google analytics to each of the pages.
=> AOTV: Add google analytics (#500)

cmd/ausoceantv/webapp/policies/privacy.html, cmd/ausoceantv/webapp/policies/terms-of-service.html, cmd/ausoceantv/webapp/src/web-components/app-header.ts, cmd/ausoceantv/webapp/vite.config.ts
This was done so that policies were properly handled and addressed in vite.
=> AOTV: Update vite config and paths

cmd/oceanbench/broadcast.go, cmd/oceanbench/main.go, cmd/oceantv/broadcast_hardware_machine.go, cmd/oceantv/main.go
This is just here for review, will make a proper fix before a PR
=> Fix broadcast voltage pin usage

cmd/ausoceantv/main.go, cmd/ausoceantv/webapp/package.json, cmd/ausoceantv/webapp/src/survey.ts
This change checks for empty responses in user survey submissions to avoid json parsing errors, as well as handling error responses better so that users can see why the error occured.
=> AOTV: Fix parsing and error handling for user survey

backend/session.go, gauth/userauth.go
This change correctly sets the maxage of cookies.
=> Backend: Set the maxage of a new session (#511)

gauth/userauth.go
This change removes the approval force option which forces the user to consent to all scopes every time they log in. This reduces the friction for a user to login.
=> Gauth: remove ApprovalForce option (#510)

model/feed.go, model/model_test.go
This change adds the following methods to the feed entity:
- GetFeed - Gets feed by ID
- CreateFeed - Creates a feed or returns an error
- UpdateFeed - Updates a feed or returns an error
- DeleteFeed - Deletes a feed by ID
- GetAllFeeds - Gets all feeds in the store
=> Model: Add basic feed methods.

backend/handler.go, cmd/oceanbench/main.go, cmd/oceanbench/rollup.config.js, cmd/oceanbench/set.go, cmd/oceanbench/t/set/cron.html, cmd/oceanbench/ts/cron-settings.ts, cmd/oceantv/broadcast_hardware_machine.go, cmd/oceantv/broadcast_machine.go, cmd/oceantv/main.go, gauth/userauth.go, model/feed.go, model/model_test.go
This change adds support to the gauth library for the newer method of google signins. Either through the onetap method, or the signin with google button.
=> Gauth: Add support for google login (onetap/signin with google)

model/feed.go
This change adds a couple of helper functions to the feed entity for accessing and editing the source and source type.
This will be useful when updating the source of a Feed on AOTV.
=> Model: Add helper functions to feed

model/model_test.go, model/subscriber.go
This was done to allow the retrieval of all subscribers from the datastore.
This will be used for AusOceanTV statistics.
=> model: add GetAllSubscribers

cmd/oceanbench/text.go
=> bench: check for empty text result to prevent panic

cmd/datablue/handlers.go, cmd/datablue/main.go
And var requests no longer do so.
Implements Issue #562.
=> Poll requests now update variables supplied by the client

cmd/oceanbench/main.go, model/sensor.go
This change updates the pin number to A36 for reading the power 3 voltage. This change reflects the change in the PCB.
=> System: Update Power 3 Pin number

model/factories.go
This change adds the required factories to create the default variables for a camera.
=> Model: Add Camera variable factories (#195)

cmd/oceanbench/s/configure.js
This change fixes the error where the server receives a broken pipe error when redirecting from the configuration page.
closes #610
=> Bench: Fix redirect broken pipe error

exp/featureflags/main.go
This little program is intended to show how feature flags might work.
The key function is `FeatureFlagMiddleware`. Everything else is just mock data.
=> Feature flag experiment

exp/uploader/main.go, exp/uploader/t/upload.html
This is a proof of concept media uploader.
Media is uploaded to a unique Google Storage Bucket object named:
`ausoceantv-ugc/username/filename`.
Media is currently uploaded "as is" without any checks. It is envisioned that uploaded content should be verified by a separate web service (or manually) before before being upload to YouTube or elsewhere.
=> Media uploader
